# Generated by Django 5.1.7 on 2025-03-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='public_id',
        ),
    ]
